# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-08 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=250, verbose_name='\u6807\u9898')),
                ('contact', models.TextField()),
                ('picture', models.ImageField(upload_to='uploadImages', verbose_name='\u56fe\u7247')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
            ],
        ),
    ]
