# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-08 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_car',
            name='carcount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users_car',
            name='isvisite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users_car',
            name='mulitple',
            field=models.IntegerField(),
        ),
    ]
